[program:galika-application]
command=php /var/www/work-lancer/artisan galika:daemon --sleep=1 --lease=50
directory=/var/www/work-lancer
autostart=true
autorestart=true
startretries=100
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/galika-application.log
stderr_logfile=/var/log/galika-application.err.log

[program:galika-outbox]
command=php /var/www/work-lancer/artisan galika:outbox-worker --limit=50 --sleep=2
directory=/var/www/work-lancer
autostart=true
autorestart=true
startretries=100
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/galika-outbox.log
stderr_logfile=/var/log/galika-outbox.err.log

[program:galika-inbound]
command=/bin/sh -c "while true; do php /var/www/work-lancer/artisan galika:inbound; sleep 30; done"
directory=/var/www/work-lancer
autostart=true
autorestart=true
startretries=100
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/galika-inbound.log
stderr_logfile=/var/log/galika-inbound.err.log
