[program:galika-application]
command=php /var/www/work-lancer/artisan galika:daemon --sleep=1 --lease=50
directory=/var/www/work-lancer
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/galika-application.log
stderr_logfile=/var/log/galika-application.err.log

[program:galika-outbox]
command=php /var/www/work-lancer/artisan galika:outbox-worker --limit=50 --sleep=2
directory=/var/www/work-lancer
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/galika-outbox.log
stderr_logfile=/var/log/galika-outbox.err.log
