<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
 public function up(): void {
  Schema::create('galika_opportunities', function(Blueprint $t){$t->id();$t->string('canonical_key')->unique();$t->string('source');$t->string('external_id')->nullable();$t->string('employer');$t->string('title');$t->string('location')->nullable();$t->string('url',2048);$t->longText('description')->nullable();$t->timestamp('published_at')->nullable();$t->timestamp('discovered_at');$t->timestamp('verified_at')->nullable();$t->string('eligibility')->default('UNKNOWN');$t->unsignedTinyInteger('match_score')->default(0);$t->json('evidence')->nullable();$t->timestamps();});
  Schema::create('galika_applications', function(Blueprint $t){$t->id();$t->foreignId('opportunity_id')->constrained('galika_opportunities')->cascadeOnDelete();$t->string('application_key')->unique();$t->string('status')->index();$t->string('route')->nullable();$t->string('blocker')->nullable();$t->timestamp('started_at')->nullable();$t->timestamp('submitted_at')->nullable();$t->timestamp('confirmation_at')->nullable();$t->longText('submission_proof')->nullable();$t->string('confirmation_id')->nullable();$t->string('delivery_state')->nullable();$t->longText('delivery_evidence')->nullable();$t->timestamp('delivery_reconciled_at')->nullable();$t->string('inbound_state')->nullable();$t->longText('inbound_evidence')->nullable();$t->unsignedInteger('attempt_count')->default(0);$t->unsignedInteger('discovery_to_submit_sec')->nullable();$t->timestamps();$t->unique('opportunity_id');});
  Schema::create('galika_application_answers', function(Blueprint $t){$t->id();$t->foreignId('application_id')->constrained('galika_applications')->cascadeOnDelete();$t->string('question_hash',64);$t->text('question');$t->longText('answer');$t->string('answer_type')->default('FREE_TEXT');$t->boolean('humanized')->default(true);$t->text('source_basis');$t->timestamp('submitted_at')->nullable();$t->timestamps();$t->unique(['application_id','question_hash']);});
  Schema::create('galika_decisions', function(Blueprint $t){$t->id();$t->foreignId('application_id')->nullable()->constrained('galika_applications')->nullOnDelete();$t->string('decision_type');$t->text('question');$t->json('context')->nullable();$t->string('status')->default('OPEN')->index();$t->longText('answer')->nullable();$t->timestamp('resolved_at')->nullable();$t->timestamps();});
  Schema::create('galika_platform_health', function(Blueprint $t){$t->id();$t->string('platform')->unique();$t->string('health')->default('UNKNOWN');$t->string('circuit_state')->default('CLOSED');$t->unsignedInteger('consecutive_failures')->default(0);$t->timestamp('last_checked')->nullable();$t->timestamp('last_success')->nullable();$t->timestamp('retry_after')->nullable();$t->text('last_error')->nullable();$t->timestamps();});
  Schema::create('galika_execution_work_items', function(Blueprint $t){$t->id();$t->uuid('correlation_id')->unique();$t->string('idempotency_key')->unique();$t->string('kind')->index();$t->json('payload');$t->string('status')->default('QUEUED')->index();$t->unsignedInteger('attempts')->default(0);$t->timestamp('available_at')->nullable();$t->timestamp('leased_until')->nullable();$t->text('last_error')->nullable();$t->timestamps();});
  Schema::create('galika_learning_log', function(Blueprint $t){$t->id();$t->string('engine');$t->text('hypothesis')->nullable();$t->longText('evidence');$t->string('outcome');$t->text('model_update')->nullable();$t->decimal('confidence',5,4)->default(0);$t->timestamps();});
 }
 public function down(): void { foreach(['galika_learning_log','galika_execution_work_items','galika_platform_health','galika_decisions','galika_application_answers','galika_applications','galika_opportunities'] as $x) Schema::dropIfExists($x); }
};
