<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
 public function up():void{
  Schema::create('galika_employers',function(Blueprint $t){$t->id();$t->string('canonical_name')->index();$t->string('domain')->nullable()->index();$t->string('industry')->nullable();$t->string('country')->nullable();$t->json('memory')->nullable();$t->json('trust')->nullable();$t->timestamp('cooldown_until')->nullable();$t->timestamps();});
  Schema::create('galika_people',function(Blueprint $t){$t->id();$t->foreignId('employer_id')->nullable()->constrained('galika_employers')->nullOnDelete();$t->string('name');$t->string('role')->nullable();$t->string('email')->nullable()->index();$t->string('linkedin_url')->nullable();$t->string('relationship_type')->nullable();$t->json('metadata')->nullable();$t->timestamps();});
  Schema::create('galika_relationships',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('person_id')->constrained('galika_people')->cascadeOnDelete();$t->string('strength')->default('UNKNOWN');$t->string('state')->default('KNOWN');$t->timestamp('last_contact_at')->nullable();$t->json('evidence')->nullable();$t->timestamps();$t->unique(['user_id','person_id']);});
  Schema::create('galika_campaigns',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('employer_id')->nullable()->constrained('galika_employers')->nullOnDelete();$t->foreignId('opportunity_id')->nullable()->constrained('galika_opportunities')->nullOnDelete();$t->string('strategy')->default('ATS');$t->string('state')->default('ACTIVE');$t->json('plan')->nullable();$t->decimal('expected_value',12,4)->nullable();$t->timestamp('next_action_at')->nullable();$t->timestamps();});
  Schema::create('galika_conversations',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('application_id')->nullable()->constrained('galika_applications')->nullOnDelete();$t->foreignId('campaign_id')->nullable()->constrained('galika_campaigns')->nullOnDelete();$t->string('channel');$t->string('direction')->nullable();$t->string('external_thread_id')->nullable()->index();$t->string('classification')->nullable();$t->text('body')->nullable();$t->timestamp('occurred_at')->nullable();$t->json('metadata')->nullable();$t->timestamps();});
  Schema::create('galika_personas',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('headline')->nullable();$t->json('target_roles')->nullable();$t->json('emphasis')->nullable();$t->decimal('performance_score',8,4)->nullable();$t->boolean('active')->default(true);$t->timestamps();});
  Schema::create('galika_interviews',function(Blueprint $t){$t->id();$t->foreignId('application_id')->constrained('galika_applications')->cascadeOnDelete();$t->string('stage')->default('INTERVIEW');$t->string('state')->default('SCHEDULED');$t->timestamp('starts_at')->nullable();$t->string('timezone')->nullable();$t->string('meeting_url')->nullable();$t->json('interviewers')->nullable();$t->json('prep_plan')->nullable();$t->json('outcome')->nullable();$t->timestamps();});
  Schema::create('galika_offers',function(Blueprint $t){$t->id();$t->foreignId('application_id')->constrained('galika_applications')->cascadeOnDelete();$t->string('state')->default('RECEIVED');$t->decimal('base_comp',16,2)->nullable();$t->string('currency',3)->nullable();$t->decimal('bonus',16,2)->nullable();$t->text('equity')->nullable();$t->json('benefits')->nullable();$t->timestamp('deadline_at')->nullable();$t->json('analysis')->nullable();$t->timestamps();});
  Schema::create('galika_outcomes',function(Blueprint $t){$t->id();$t->foreignId('application_id')->constrained('galika_applications')->cascadeOnDelete();$t->string('type');$t->string('stage')->nullable();$t->string('reason')->nullable();$t->json('evidence')->nullable();$t->timestamp('occurred_at')->nullable();$t->timestamps();});
  Schema::create('galika_events',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('kind');$t->string('title');$t->string('location')->nullable();$t->timestamp('starts_at')->nullable();$t->text('url')->nullable();$t->json('companies')->nullable();$t->json('people')->nullable();$t->json('notes')->nullable();$t->timestamps();});
  Schema::create('galika_answer_knowledge',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('intent')->index();$t->text('canonical_question')->nullable();$t->text('answer');$t->string('scope')->default('GLOBAL');$t->timestamp('valid_until')->nullable();$t->json('provenance')->nullable();$t->boolean('material')->default(false);$t->timestamps();});
  Schema::create('galika_privacy_rules',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('data_type');$t->string('stage');$t->boolean('allowed')->default(false);$t->json('conditions')->nullable();$t->timestamps();$t->unique(['user_id','data_type','stage']);});
  Schema::create('galika_work_authorizations',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('country');$t->string('status');$t->boolean('sponsorship_required')->default(false);$t->boolean('remote_contractor_ok')->default(false);$t->boolean('eor_ok')->default(false);$t->boolean('willing_to_relocate')->default(false);$t->json('evidence')->nullable();$t->timestamps();$t->unique(['user_id','country']);});
  Schema::table('galika_opportunities',function(Blueprint $t){$t->foreignId('employer_id')->nullable()->after('id')->constrained('galika_employers')->nullOnDelete();$t->string('lineage_key')->nullable()->index();$t->string('trust_state')->nullable()->index();$t->decimal('expected_value',12,4)->nullable();$t->timestamp('reverified_at')->nullable();});
  Schema::table('galika_applications',function(Blueprint $t){$t->string('submission_state_detail')->nullable();$t->string('correction_state')->nullable();$t->foreignId('persona_id')->nullable()->constrained('galika_personas')->nullOnDelete();});
 }
 public function down():void{
  Schema::table('galika_applications',fn(Blueprint $t)=>$t->dropConstrainedForeignId('persona_id'));
  Schema::table('galika_applications',fn(Blueprint $t)=>$t->dropColumn(['submission_state_detail','correction_state']));
  Schema::table('galika_opportunities',fn(Blueprint $t)=>$t->dropConstrainedForeignId('employer_id'));
  Schema::table('galika_opportunities',fn(Blueprint $t)=>$t->dropColumn(['lineage_key','trust_state','expected_value','reverified_at']));
  foreach(['galika_work_authorizations','galika_privacy_rules','galika_answer_knowledge','galika_events','galika_outcomes','galika_offers','galika_interviews','galika_personas','galika_conversations','galika_campaigns','galika_relationships','galika_people','galika_employers'] as $x)Schema::dropIfExists($x);
 }
};